author = "wklchris"
copyright = "wklchris"
exclude_patterns = ['_build', '**.ipynb_checkpoints']
extensions = ['nbsphinx', 'sphinx_copybutton', 'sphinx.ext.mathjax']
html_css_files = ['style.css']
html_static_path = ['../_static']
html_theme = "sphinx_rtd_theme"
html_theme_options = {'canonical_url': "https://wklchris.github.io/blog/Matplotlib/"}
language = "zh_CN"
project = "Matplotlib"
smartquotes = False
templates_path = ['../_templates']
year = 2020