author = "wklchris"
copyright = "wklchris"
exclude_patterns = ['_build', '**.ipynb_checkpoints']
extensions = ['nbsphinx', 'sphinx_copybutton', 'sphinx.ext.mathjax']
html_css_files = ['../../_static/style.css', 'roofpig.css']
html_js_files = ['roofpig_and_three.min.js']
html_static_path = ['_static']
html_theme = "sphinx_rtd_theme"
html_theme_options = {'canonical_url': 'https://wklchris.github.io/Rubik/'}
language = "zh_CN"
project = "Rubik"
smartquotes = False
templates_path = ['../_templates']
today_fmt = "%Y-%m-%d"
year = 2022